spring.application.name=taskpilot
spring.datasource.url=jdbc:mysql://localhost:3306/taskpilot
spring.datasource.username=root
spring.datasource.password=sql01
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true